// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jpiqubhwpoqukqapsstp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpwaXF1Ymh3cG9xdWtxYXBzc3RwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU3MjQxNTksImV4cCI6MjA1MTMwMDE1OX0._TZ6yjGrQiTEnz0FQceXyH_x1WqxCMgUsHVuyrRBArc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);